### ISSUE TITLE
MYSQL 5.7 requires GROUP by

### ISSUE THREAD

**Issue by phreesoft** [phreebooks/PhreeBooksERP#224]
Sent to me by a PhreeBooks user:

It seems newer version of MySQL requires GROUP BY when using grouping
functions like max/min/avg etc.

I fixed it for inventory.php
See my pasted git diff below.

Btw is there any way i can clone phreebooks via git so i can easily
merge your upgrades with my own code? (I know of the ease
customization with special files)

diff --git a/modules/inventory/functions/inventory.php
b/modules/inventory/functions/inventory.php
index 5606709..3a9ab9d 100644
--- a/modules/inventory/functions/inventory.php
+++ b/modules/inventory/functions/inventory.php
@@ -244,10 +244,10 @@
// get the inventory prices
if($type == 'v'){
if ($contact_id) $inventory = $db-_Execute("select p.item_cost,
a.full_price, a.pr
- else $inventory = $db-_Execute("select MAX(p.item_cost) as
item_cost, a.full_price
+ else $inventory = $db-_Execute("select MAX(p.item_cost) as
item_cost, a.full_price
$inv_price_sheet = $inventory-_fields['price_sheet_v'];
}else{
- $inventory = $db-_Execute("select MAX(p.item_cost) as item_cost,
a.full_price, a.p
+ $inventory = $db-_Execute("select MAX(p.item_cost) as item_cost,
a.full_price, a.p
$inv_price_sheet = $inventory-_fields['price_sheet'];
}
// set the default tax rates
@@ -366,4 +366,4 @@ function validate_EAN13Barcode($barcode) {
return false;
}

**Comment by ReneKervezee** [comment]
Dave i have been looking in to this but it isn't true.
If you use a 'group by' on a max query you get the highest value of each grouped element.

In the case of the inventory functions file we only want the highest cost of one sku. 
The current function is faster with less overhead.
and the code would require a major rewrite because the query would return a array of sku's instead of one.

I now work with 'eclipse mars' in combination with github. 
Eclipse allows me to do all github functions within eclipse.
But i keep using winmerge to update my working environment.

**Comment by phreesoft** [comment]
OK, I'll close this. Thanks for looking into this.

Dave
