### ISSUE TITLE
Is PhreeBooks still supported?

### ISSUE THREAD

**Issue by rridley** [phreebooks/PhreeBooksERP#231]
Phreesoft webpage no longer exists (and hasn't for nearly 4 months) and the forums that were there also don't exist. I'm trying to decide if I need to start looking for another program or if this one will continue in some form?

**Comment by bryandale** [comment]
Good question. The original developer has a commercial product called Bizuno that he is selling and do is no longer supporting Phreebooks, but Phreebooks appears to live on here and on Sourceforge to the extent that there are others supporting this as an open source project. For whatever that's worth.

**Comment by alvin101** [comment]
I do believe that Rene Kervezee is our only dev at the moment. It sure would be good to see some other talent come forward, as Rene is very busy with other work.

**Comment by phreesoft** [comment]
Hi All, I'm sorry to have reached this point with PhreeBooks. I have put in over ten years on this project and thousands upon thousands of free hours. In return I have not received enough donations to start to cover the hard costs, SSL certificates, servers/hosting, etc. I completely re-wrote the PhreeBooks code for Bizuno which I was hoping would catch on better, being hosted and all. As of this writing, Bizuno has had a modest return, just barely covering my hard costs. I could go on for a while as to why PhreeBooks and Bizuno didn't get traction but I won't. A lot of lessons learned but the reality is there is no money in the open source world, it relies on all it's hours from volunteers. For me, it got to the point where I can't spend this much time and aside from a little support from the community, I have been on my own since inception. Rene, Alvin, Charles and a few others have provided some peripheral support but that's pretty much it. 

So I'm at the point where I decided to release Bizuno as a scaled down application for WordPress alongside a stand alone version and the current hosted version. I will offer extensions at a very reasonable price and see how that goes. Gone are my aspirations to make it big. Now Bizuno is in 'hobby' status. I will provide a forum and KB, replacing the PhreeBooks one and go from there. Expect a new cleaner, leaner website next month with just the highlights. I will accept donations but have no expectations. I will also offer a support plan at around $300/year. I will also include a conversion script in the base version to move from PhreeBooks R3.7 to Bizuno. 

Dave Premo, PhreeSoft

**Comment by rridley** [comment]
@Dave,
I've donated before and wouldn't mind doing again. I wish you had a webpage up where donations could be made :-(

**Comment by phreesoft** [comment]
I’m working on the new PhreeSoft.com <http://phreesoft.com/> web site. I have added a donation page. I haven’t tested it yet but it’s a standard module for Wordpress and I don’t expect any issues. I should have it tested by the end of the day.

David Premo, PhreeSoft
E: dave.premo@phreesoft.com
W: www.PhreeSoft.com

**Comment by charles2** [comment]
Hi Dave, Rene, Alvin et al,
I also have been too busy to further address PhreeBooks.

I must say that I think that Dave has done an excellent job with PhreeBooks over the years and it was slowly (perhaps much too slowly) gaining traction. IMHO it is excellent. I have been running it for my little business and it is rock-solid so far ('testing' 2yrs and 'live' 3 yrs). You can see, I am a 'believer', however, most people don't have the luxury of my patience.

None of my opinions have changed about where PB should be headed. I agree with Dave that the Open-Source area is v hard to make any money in. But I honestly believe that PB took a wrong turn with Bizuno. It moved markets abruptly into an area where I felt that  it was never going to be able to compete (I would have loved to have been proven wrong). The likes of Xero, Sage and QB Online have it well sown up and there is HUGE investment not making any returns - and will not make decent returns for a long time. There IS IMHO an opportunity with the SME businesses who are revolted at the idea of turning there data over to big-bookkeeping. There is also an opportunity in very sector-specific SME's e.g. Volusion web-store SME's (there are many, many similar opps).

The learning curve for new users to PB was way too steep with little written documentation for them to refer to. This improved over time, but was always a weakness (and I presume still is). I tried to write a new 'How-To' every weekend for over a year - an improvement, but still not enough. However, the old website ranked spectacularly well in Google for some of the odd things that we talked about.

It is painful for me to watch the modest advances that we made so easily given up. It is SO time-consuming to create something and it is destroyed SO quickly. Personally, I feel a personal loss when I see PB faltering. There IS a need out there - fair-minded SME owners want a fair-minded simple bookkeeping package - PB was it, but it takes time and a commonly shared understanding of the goal. People ARE prepared to donate / spend modest sums on a 'local data' bookkeeping package IMO but it needs to address a specific need.

Anyway, I am still here. Sitting at the back sipping a cup of tea quietly.

**Comment by bryandale** [comment]
The big accounting packages can be expensive with monthly fees for the program and Addons continuing indefinitely. When I cancelled Xero to move to Phreebooks, I lost access to all my old records as well. There are other free or low cost options like Wave accounting and Zoho Books also in the mix. 

I appreciated the work Dave has done and he has helped me several times, but I am totally turned off by the monthly fee model and hosted solutions. My switch to Phreebooks was part of a move from Shopify to Opencart also to save the high ongoing costs. Once you're set up, the need for support diminishes greatly over time yet the costs continue indefinitely.

Phreebooks is the only open source accounting that integrates with opencart. That is a significant selling point, or at least it was for me. I would have been willing to pay more than the $25 Dave charged for that feature, but I would never agree to an ongoing monthly charge.

It would be nice to see Phreebooks development continue. The Bizuno fork really is an unfortunate step in the wrong direction.

Bryan

Urbanrider.ca

**Comment by charles2** [comment]
Hmmmm. I don't think that it is as clear as all that. Also, for me is it less about the 'monthly fee model' (which I think that we all hate) and MUCH more about having control of your data. Unfortunately, people only realise too late how important this is. Like you describe with your experience with Xero. Your data is invaluable - just imagine if you have an HMRC / IRS investigation and you don't have your data to refer to - you're screwed. These investigations can happen v easily in the UK up to 6yrs into the past. If you are accused of 'wrongdoing' it can be 20 years!!! You NEED your data.

I always knew that Dave's plan was to monetize PB and I regarded that as only fair. He had put in a huge time investment and if PB could have given him a nice pension then all well and good. However, the plain vanilla on-line bookkeeping market-space is wayyyyy too overcrowded - with big hungry rich corporates plashing the $$$ about.

There ARE a group of tech savvy SME businesspeople who recognise the (many) drawbacks of the 'cloud' nonsense and the 'Hotel California' cloud bookkeeping software (difficult to leave) who would value PB. There ain't no gold in these here hills IMO, but there is a v modest market that the big boys will never find economical.

**Comment by charles2** [comment]
BTW Bryan,

How have you found OpenCart?
There was talk, back before v2.0, that the SEO facilities in OpenCart were lacking and that CS-Cart and PrestaShop were more powerful (they all have their pro's and con's though)?

**Comment by bryandale** [comment]
I have version 2.1 and the SEO is ok. The main issue I have had is its inability to handle multiple options adequately (e.g. Size and colour). There are extensions available but they all have issues. The one I use doesn't work well with my point of sale extension for example so I have to manually update inventory levels. The lack of support for multiple options is the biggest design flaw in the platform. 

I've been planning on setting up a test with Magento to compare features but I haven't got around to it. I don't think I would change systems again without spending some time working with a test site to confirm it has all the features I need.

Bryan

Urbanrider.ca

**Comment by charles2** [comment]
Bryan, thanks for the response.

...  perhaps this is an example of just what I was talking about earlier. This issue of SKU / size / colour is a BIG problem with most webshop-bookkeeping software interfaces = opportunity for PB.

**Comment by bryandale** [comment]
The problem I was describing was really with opencart not the accounting interface. Typically every size and colour variation is given a unique part number by manufacturers and wholesale distributors. Ideally those part numbers would be used on the retail web site. The trouble with opencart is it only allows a single identifying number to be used for the product, including all of its size and colour variations. For accounting purposes that's adequate so long as the costs of the different variations are the same. If they are different, then cost of goods sold end up being calculated incorrectly and inventory isn't tracked properly unless you create a new product for each variation. For example, some of the motorcycle helmets I sell come in different finishes that sell at different prices. I usually show them as one helmet with options to select finish and size. The trouble is opencart is incapable of tracking two characteristics at a time. It only reports one helmet as being sold but can't say which size and finish. That gets carried through to the accounting software which reports the cost of sales based on fifo for a mixed bag of helmets in different sizes and finishes. The actual sale may have been of the cheapest finish, but the cost appears following FIFO for a helmet of higher cost.

Bryan

Urbanrider.ca

**Comment by charles2** [comment]
Yes, that sounds complicated. I don't think that this thread is the place to further discuss this particular issue. The old PB forum is no more (unfortunately), but if you wish to discuss this issue further, perhaps  a new thread or a post on Dave's brand new Bizuno forum:
https://www.phreesoft.com/forums/

Actually, I can't work out how to sign up - so do it here if you want it discussed further. No promises that I will be able to help though.

**Comment by phreesoft** [comment]
Hi All,

I have been monitoring this forum and would be willing to create a new forum for PhreeBooks discussions. I haven’t finished setting up the new site, hopefully 
this upcoming week and there will be a login page. For now, if you go to My Account at the store, there is a place to create a new account and you should be able to post in the forum. If you have a problem, send me an email. I’ll try to set up a forum to post to tomorrow.

I’m in the final process of preparing Bizuno for public release. Bizuno is a major overhaul of PhreeBooks and has a completely new architecture. It’s faster, lighter and much easier to customize. I am finishing work on the Wordpress plugin version. It will run in parallel with WordPress but use the upgrade engine provided with WordPress. Should be much easier for everyone to keep up with the latest. I will also be releasing a open source version. FYI, I have a script to convert your db and files from the latest PhreeBooks R3.7. The reports are imported as I have made too many changes to the format and the conversion typically creates more problems than it fixes.

Dave

**Comment by charles2** [comment]
Hi Dave,

I probably have too many questions. Where to start. Perhaps I should number them. I hope that you don't mind:

(1) "Bizuno ...  Wordpress plugin version" how does this work? Does it run 'in' Wordpress or is it stand-alone or just use the excellent Wordpress Upgrade Engine?
(2) I presume that you last line should read - "The reports are NOT imported as ..."
(3) "Bizuno is a major overhaul ..." what are the headlines from a PB users point of view?
(4) Have you added the feature to somehow 'lock' previous years - to avoid changes / additions / deletions to previous years (already reported to tax authority). This is an annoying issue that I have suffered from with PB.
(5) Have you copied the excellent PB Journal Entry screen with the automatically appearing 'this account will increase' and 'this account will decrease' messages. When I saw an early beta of Bizuno it wasn't the fully featured excellent PB one yet.
(6) and the question I am avoiding   ...   obviously there is going to be a period of change ahead for PB / Bizuno. How they will both fit together (if at all) isn't totally clear to me - especially as Rene / PBv4.0 is somewhere in the picture also. So  the question  ...   Are you really proposing to move ahead with 2x names:
PhreeBooks - been around  few years. An improvement on Phreedom (IMHO). Personally I like the name - it speaks to me (maybe just because I am familiar with it). It was a real contender in it's space - recently suffered badly (just look at the download graph on S'Forge)
Bizuno - It can't be as well known. It doesn't really say anything to me (perhaps because I am unfamiliar with it).

Is there a cunning strategy to all this? Perhaps there ought to be, if not.

I am sure that others have as many questions as I do.
Charles

**Comment by phreesoft** [comment]
See answers within.

> On May 8, 2017, at 1:21 PM, charles2 <notifications@github.com> wrote:
> 
> Hi Dave,
> 
> I probably have too many questions. Where to start. Perhaps I should number them. I hope that you don't mind:
> 
> (1) "Bizuno ... Wordpress plugin version" how does this work? Does it run 'in' Wordpress or is it stand-alone or just use the excellent Wordpress Upgrade Engine?
> 
It runs in parallel but is loaded within the plugin folder so I can use their upgrade system. I will be setting up a repository at the wordpress site to control revisions. Also, one of the biggest problems I had with PhreeBooks was server setup. This should get around the issue. 
> (2) I presume that you last line should read - "The reports are NOT imported as …"
> 
Yup. I have made standardization changes to the reports. I can convert them but it seems that every time I run a conversion there are problems. It’s easier to just redo them.
> (3) "Bizuno is a major overhaul ..." what are the headlines from a PB users point of view?
> 
I made a wholesale change to the architecture. The Phreebooks core functionality is intact (with more bug fixes). I also upgraded the db engine to PDO as the mysql has been deprecated in newer versions of PHP.
> (4) Have you added the feature to somehow 'lock' previous years - to avoid changes / additions / deletions to previous years (already reported to tax authority). This is an annoying issue that I have suffered from with PB.
> 
I don’t have this feature but it is extremely easy to add through the hooks. I will be doing an extensive write-up on how to use the hooks and customize Bizuno. Super easy and mods don’t step over each other. Also no mods to core code.
> (5) Have you copied the excellent PB Journal Entry screen with the automatically appearing 'this account will increase' and 'this account will decrease' messages. When I saw an early beta of Bizuno it wasn't the fully featured excellent PB one yet.
> 
Yes, and the arrows are there. I also added the capability to write a check from a gl entry if there is a accounts payable line to ping off of. This allows me to hide the gl from everyone and make payments that aren’t visible to my employees.
> (6) and the question I am avoiding ... obviously there is going to be a period of change ahead for PB / Bizuno. How they will both fit together (if at all) isn't totally clear to me - especially as Rene / PBv4.0 is somewhere in the picture also. So the question ... Are you really proposing to move ahead with 2x names:
> PhreeBooks - been around few years. An improvement on Phreedom (IMHO). Personally I like the name - it speaks to me (maybe just because I am familiar with it). It was a real contender in it's space - recently suffered badly (just look at the download graph on S'Forge)
> Bizuno - It can't be as well known. It doesn't really say anything to me (perhaps because I am unfamiliar with it).
> 
This is a good question, I started on Bizuno as a commercial venture. I had reached a point with PhreeBooks where I didn’t want to work for free any more. I was spending 20-30 hours a week, ignoring my real business that was paying my bills. I wanted to see if I could build something that would sell. At the same time Rene had started working on Release 4. So I developed Bizuno and let Rene go off and develop R4. Needless to say, and mostly due to lack of funding (I tried to go the self funded route and didn’t have the capital I needed to get it right), Bizuno struggled. Late last  year, I decided to see what I could do to put Bizuno out there as open source with paid modules to extend the capability. By this time, Rene was well along with PhreeBooks R4.0 and I didn’t want all his efforts to got for naught. I need to cut down the time I spend on these projects. I have invested over 10 years of volunteer labor and I just can’t do it anymore. 

So where I’m at is Rene will need to take over as project lead for PhreeBooks. I will focus the next several months bringing Bizuno to the open source market. I will not do any more unpaid customization and, with the new architecture, I’m hoping my time spent wall be much less. 

BTW, Phreedom and PhreeBooks were always the same. It was a thought I had years ago to turn PhreeBooks into an accounting engine and Phreedom was suppose to be the ERP package. It didn’t catch on and I dropped Phreedom. I have spent the last few months converting Bizuno into a library which can be easily added to any framework (loosely) and run in parallel. 

Dave

**Comment by alvin101** [comment]
@phreesoft , and Bizuno, I have a few questions, or issues I have had for years...

1. I need a strong POS, with bad internet and offline support, is this implemented? 
2. Can you now closeout an accounting year?
3. Have you changed the way foreign currency transactions are done through out the systeem? 

All these issues I have brought up over the years, if I question is not understood I will elaborate,

Thanks,

Alvin

**Comment by charles2** [comment]
**Dave**,
thanks for the considered response. I really don not blame you getting fed up with the free hours - no return routine. It just isn't sustainable. However, you have invested a huge amount of time in PB and Biz, it strikes me that a holistic strategy with all efforts pulling in the same direction would be sensible. How to do this isn't immediately clear to me.

**Alvin**
Hi there. I think that your point 2. is the same as my point (4) - correct?

**Dave**
"I don’t have this feature but it is extremely easy  ...."  most accounting / bookkeeping packages that I have looked at have it. Why have you avoided it? Does it somehow impede the searchability of the data - impede Management Info or something?

I have found that when I allow other people to input data, they are just humans and make mistakes - sometimes throwing out the 'in-balance' previous years. I then don't find these errors for ages and I may have then made a report of the next year with old data, this new report now incorrect, thus making the recent submission incorrect. All very frustrating.

**Comment by alvin101** [comment]
@charles2 point 2, ya maybe, but I want it backed up and removed from the system. After an accounting year is 3 or 4 years old it is time to save/print some reports and remove the data from the system.

**Comment by charles2** [comment]
**Alvin** 
yes, I agree. However this brings up an old issue - the fact that most bookkeeping packages are designed solely to meet tax authority's reporting requirements and NOT to provide invaluable Management Info to help you fine-tune the running of your business (like the big boys spend HUGE $$$ achieving).


**Dave**
Is there a demo of the latest Bizuno? It is absolutely ages since I looked at it.

Oh and another question - please excuse my ignorance - is this latest Bizuno that uses the Wordpress upgrade system, is it possible for the SME (me) to effectively run it locally on my server under the stairs?

**Comment by phreesoft** [comment]
For year end close/block, these are two different issues. 

Bizuno does have a fiscal year purge. It is a multi-step process that took me a month to get it going. Bizuno has an interactive feature where I can chunk a large job into a bunch of smaller ones to prevent script timeouts. 

For prior year restrictions, it’s not that it’s difficult, it’s that I have never had a request or need to do this. Bizuno is a whole new type of programming where the extensions can pre-pend or post-pend the primary script. This allows reviewing the posted data BEFORE anything is actually done. This makes it easy to look at the post date and either cancel the post (with a message) or any number of other options, like allowing certain roles to work in prior fiscal years or just the last couple of months, etc. 

I do not have a demo but if you can always sign up for a free account and try it out. If you had an account prior, you can go to https://www.bizuno.com <https://www.bizuno.com/> and press the Lost Password request and get a new password sent to you. I will be cleaning out dormant accounts in the coming weeks and removing basic accounts that are inactive or that have been ‘purchased’ prior but never initialized. 

I’m working on the PhreeSoft.com <http://phreesoft.com/> website now to handle the purchase of individual extensions for the Basic account. Should have it going within a week.

David Premo, PhreeSoft
E: dave.premo@phreesoft.com
W: www.PhreeSoft.com

**Comment by bryandale** [comment]
Phreebooks is open source which helps to ensure that updates will be available at some point even if the original developer abandons it. What assurances are there that Bizuno will always be maintained even if you find it unprofitable to continue?

Bryan

Urbanrider.ca

**Comment by phreesoft** [comment]
Because I’m releasing Bizuno as open source. I have to for Wordpress so I will be creating a repository on BOTH GitHub and WordPress. If I go away, Bizuno will still be alive and I will need to decide what to do with the extensions. I will probably just add them all to the base but I’m not there yet. I plan on keeping PhreeSoft.com <http://phreesoft.com/> going for a while as a hobby. I’ve simplified it and will spend my time supporting debugging the base code and supporting users.

David Premo, PhreeSoft
E: dave.premo@phreesoft.com
W: www.PhreeSoft.com

**Comment by alvin101** [comment]
@charles2 

> "remove the data from the system ... " would make it no longer searchable I assume.
an xml or spreadsheet file would be easy to search if you every needed to. But as for me I have never searched anything over 3 years old.  I do not think keeping 3 or 4 years of data in a system would be to bad.

@phreesoft It is not very often I run into such a talented developer as yourself.  Maybe you should have gone into coding instead of batteries....  I just want to thank you for your many years of quality coding. You do deserve a much better paycheck....

**Comment by charles2** [comment]
I second Alvin101 with the "talented developer" accolade. Not just with the coding though - you combine that with a professional level knowledge of accounting. That has to be rare indeed.

**Comment by charles2** [comment]
You know, I have just had the most OUTRAGEOUS thought. Probably Waaayyyyyyy too far away from reality to be a 'flyer', but I will put it out there. This isn't a new thought - a slight change on an idea I have had since I first started with PB.

Lets face it PB / Bizuno are at a cross-roads of sorts.

(1) First thought - perhaps DP should consider setting up a 'Foundation' like Dolibarr has:
https://www.dolibarr.org/
...   the main accounting code is 'open source', but loads of different developers make their own apps - Dolibarr tests and vets them and if they are ok they join the apps list. The developer takes a cut of sales (40% rings bells - but it may be more) and the rest goes to the Dolibarr Foundation - a non-profit to develop and promote everything Dolibarr.

President Primo   ...   :)   ...   sounds good.

(2) second thought - merge Bizuno with Dolibarr, in fact replace it. This is not as batshit crazy as it sounds. Dolibarr looks great BUT it has a HUGE achilles heel - it isn't 'double-entry' and will thus NEVER be 'top-table' (taken seriously by the majority of accountants). In a very cold summary (by me) - the Dolibarr central accounting 'engine' is IMHO it's 'weakest-link'. It's CRM ideas and other developed apps tower above PB (and I guess Biz). It is never going to 'fly' with non-double-entry IMHO. However, it does have a BIG following and it otherwise a very interesting project.

IMHO where PB / Biz is strong Dolibarr is weak. Where Dolibarr is strong, PB / Biz is weak.

The (rather grumpy, I have read) main developer is the infamous  Laurent Destailleur (a French dev of AWstats fame & v-president of the Dolibarr foundation)
https://www.destailleur.fr/
https://asso.dolibarr.org/index.php/Dolibarr_foundation

Just a thought - maybe a bad one at that.
Tell me i'm mad.

**Comment by ReneKervezee** [comment]
Hi i am sorry that it took me so long to respond.
There are some issues in my personal live.

I will keep developing on 4.0.

**Comment by ReneKervezee** [comment]
The biggest problem i have / had with support is that when you have the new release in your head and screen you cant find where bugs are in the current version.

**Comment by charles2** [comment]
Hi Rene, good to hear from you. Thank you for posting. And thank you for continuing to develop PBv4.0.

@phreesoft 
I have just 'ordered' a free Bizuno a/c and tried to set it up etc. I would strongly recommend making a proper 'demo' like the old PB one. The reason is that people just don't have enough time in their lives to set up a test-instance for a quick 'look see'. I gave up when I couldn't get a CoA set-up.

Not surprisingly, I have to say that on first impressions I prefer the look & feel of PB - however, there is v likely to be a strong 'familiarity bias' in my opinion. I have been using PB a long time and like it (despite it's draw-backs). None of the Biz. input boxes are aligned on my browser (SeaMonkey v2.40) but all OK in PB.

The thing about these bookkeeping softwares is that they are complicated bits of kit. It does take a long time to work out / get used to a new one. I looked at (and trialled) many before settling on PB and despite moments of frustration am still a user despite the rocky-road that we have been following recently.

**Comment by phreesoft** [comment]
Thanks for the compliments gents. This open source stuff is a thankless job and your compliments are appreciated.

Charles, I will look into the Dollibar foundation. Sounds like a lot of work to set up and maintain but I’ll dig a bit deeper.

As far as the demo. I will explore that as well. I will only do it if I can come up with a way to wipe everything out weekly. I left the demo going on phreebooks and it was amazing how messed up everything got in just a few days. I suppose I can also enable all the extensions so everyone can see what a fully capable system can do. 

Dave

**Comment by charles2** [comment]
Dave,
I agree with the "messed up" comment about the old PB demo, but all bookkeeping demo's are the same - people just cannot resist putting in 'silly numbers' it seems to be irresistibly amusing. That said, I think all serious visitors know that and they just want to be reassured that 'stuff works' before investing further time in it all.

Personally I loved the old PB demo, even when 'messed-up'.

**Comment by ihocking** [comment]
Gents,
I have used phreebooks for 3 years now and its great for my tiny business. There are a few things I had to get my head around at first and started on la local machine with XAMPP and have since moved it to a host. All good. Happy! Great support from all in this discussion. There must be a way to get some $$ to you guys without compromising the open source aspect. As an example to operate my little business in Australia it costs $249 payable to ASIC (to keep a company registered), About $100 for domain and hosting and their are probably other incidentals on the way. My point being a payment to you of $50 per year would not be too bad now that i realise what i have. Paying $50 up front not knowing what I was getting may be a deterrent. So, could you keep working on Phreebooks and leave it being free(ish). After 1 years use (I am now hooked!) ,offer upgrades/improvements access at $40-50 per year???

**Comment by charles2** [comment]
@ihocking - thank you for your input. You are an excellent example of just the sort of person for whom PB was ideal. You were idealistic and smart enough to reject the BigB$$kkeeping data-hoarders, you were tenacious enough to keep trying to solve your problems with your PB implementation and in the end you triumphed with help from the PB Forum. You then went on and very generously gave-back by putting together a How-To on your hosting solution. And you are STILL here - just like me. We recognise what a great piece of software Dave created and he and Rene massaged into shape. I bet we are FAR from alone - I bet that there is still a huge amount of good-feeling towards PB - there is still forward momentum to PB. Dave it would be wasteful just to abandon it - the old Forum and How-To's - they were a great and valuable resource.

**Comment by charles2** [comment]
@rridley - are you still with us? we all owe this convo to you! What do you think?

**Comment by phreesoft** [comment]
I still have the HowTos written by Charles. Perhaps I’ll spend some time uploading them to the GitHub wiki. This is really all about maintenance. I need to greatly simplify the website and the forums were a lot of maintenance, fighting spam and moderating. The forum was in need of pruning and clean-up. Most of the topics were obsolete and just cluttered up the forum. I still have the db dump if anyone wants to set up the forum and take it over.

Dave

**Comment by rridley** [comment]
I'm still here and listening. I found out that I had more than one problem. I haven't been able to reach bizuno.com for more than four months and I just thought that the website was down. That's what prompted the original question.
After hearing that the site is still up, I went digging and found out that Comcast has issues. I'm on a static IP as is Bizuno.com. Something is wrong with Comcast's routing tables and I am unable to reach the website. Comcast is being a butthead and blaming Bizuno despite the tcptraceroutes I've given them showing that the packets get to Denver, then putz around about 4 routers before failing, ending back up where they entered Denver. Hopefully I'll have that issue fixed this next week.
In the meantime, I've been listening to the conversation here closely. A couple of notes:
1) Phreebooks has been my primary financial software for 5 years now. It is the core of why I am able to be self employed - Brings to mind that I haven't given enough back. Early on, I donated, but I should be doing a regular donation as it's what makes it all possible. People successfully using it should regularly support it (not just a one time donation - me included.)
2) I've stayed away from Bizuno because I want all of my data in-house. I'm not much on using the cloud. To me, (a sysadmin) the cloud is really just someone's computer in their closet and I don't know who, where, how or anything else. It comes down to trust and presently, I only trust my own closet server. I know not everyone feels that way and the cloud is sufficient for some, but I want complete control over my own data, including the physical location.)
3) I do use Wordpress and if Bizuno can be self hosted on my own servers, I'm willing to look at that, otherwise, I'm sticking with Phreebooks.
4) As part of giving back to the community, I'm willing to host the Phreebooks forum on my servers if need be. I do only have a Comcast 150Mb/s business connection (static IPs and 25Mb/s up) so I don't know if that's enough to do the job. (Of course, Comcast needs to get their act together on the routing tables first.)

**Comment by charles2** [comment]
@rridley - where are you based? Thanks for the offer of hosting the PB-Forum.

@phreesoft - I think that PhreeBooks / Bizuno needs a strategy. Also, the headlines that are relevant to users should be published. I think that the lack of clarity that PB has suffered recently had damaged the brand.

Sorry to revisit the topic, but I think that continuing with 2 names is a mistake. If there is a way to bring Bizuno and PB closer together and unify them, that would be sensible IMO. They are v similar, after all. Bring together the best of both, if possible.

I am not pretending, however, to have the solution.

**Comment by charles2** [comment]
Whatever strategy is developed should have **sustainability** as a central theme. People aren't going to be interested in a project that isn't likely to be around longer-term.

**Comment by ihocking** [comment]
If I could help in someway I would be delighted. Not sure what I could do - moderator on the forum maybe? - I still think you (Dave) and others should put their mind to a few items that can / should be addressed.
providing some $ support for the project
providing some hours
keeping the brand (as charles has said)
what are the major issues?

1. Providing some $ for the project
2. Providing some hours
3. Getting some direction
4. having a plan

Again, if i could help that would be great but i feel as though i may not have the competencies required.

**Comment by phreesoft** [comment]
After conversing with Rene I have reached the following decision:

Rene will continue to develop Release 4.0, which may be a while and will have the look and feel he creates. He has other priorities that are pulling him away and his ability to support the project is limited. Therefore, I will not interfere with this release as I cannot control the main development branch.

PhreeSoft (Dave) will convert my current Bizuno code to a library under another project name. I will create a stand-alone version of PhreeBooks based on the Bizuno library (which also includes the PhreeBooks accounting module) and include the necessary portal code to allow stand-alone operation. I will also include the PhreeBooks upgrade script to convert earlier PhreeBooks databases to the new structure. I will re-configure the PhreeSoft website to have a new section for the PhreeBooks branch.

**Comment by alvin101** [comment]
We have 21 users watching this.  I know the talented Dave is no longer support, and Rene hardly has the time to work on this.

I do not like any of the other erp's as much as I like this one.

So I would like to make a call to Rene and the others like me who want to see this go forward.

Lets make a plan, hire some freelancers and do or die.

Please come back with a vote....

**Comment by rpcohen64** [comment]
Good morning friends
While I personally found from my use of phreebooks that it was a very
capable product ready for use by a semiskilled admin, I do not want to vote
to push support from admins and design and coders who can no longer devote
time to what amounts to a hobby for them. They worked many years on this
project with input from users like you and I . I still follow the group
pages in hopes of possible revival in the future. Wether that comes from
previous or new volunteer admins. A huge thanks for all those who worked
and contributed along the way. And Happy Holidays to all.
Cheers
Bob

On Dec 28, 2017 11:18 AM, "Alvin" <notifications@github.com> wrote:

We have 21 users watching this. I know the talented Dave is no longer
support, and Rene hardly has the time to work on this.

I do not like any of the other erp's as much as I like this one.

So I would like to make a call to Rene and the others like me who want to
see this go forward.

Lets make a plan, hire some freelancers and do or die.

Please come back with a vote....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/phreebooks/PhreeBooksERP/issues/231#issuecomment-354313734>,
or mute the thread

**Comment by phreesoft** [comment]
So this is my latest plan. I have been approved to offer Bizuno for WordPress through the WordPress repository. This means the basic version of Bizuno is now in open source status. With this, I plan on jumping over PhreeBooks R4 to PhreeBooks R5 which will be a modified version of Bizuno for WordPress. The code is basically ready, I just need to code up an update script for future releases. I want it to be seamless for the user.

I should have the WordPress version listed in their repository sometime in January 2018 and will follow in a few weeks with PhreeBooks 5 here. PhreeBooks 5 will include a script to upgrade PhreeBooks R3.7 databases and a translator assistant. 

PhreeSoft (and I) will not support PhreeBooks version below version 5 except with assistance converting to the latest version. I will also close out all open issues here related to any version prior to PhreeBooks 5.

Dave
