### ISSUE TITLE
phreebooks trial balance is out of balance

### ISSUE THREAD

**Issue by fguzman84** [phreebooks/PhreeBooksERP#239]
Dear Team.

I have the following error:

> Trial balance is out of balance (This can usually be fixed by re-posting the transaction). Debits=   and credits=  in period 8

Is it possible that someone can assist us?
We are desperate and we do not know how to solve it.
Best Regards!
![phreebooks trial balance error](https://user-images.githubusercontent.com/31140022/29471066-4430af46-8414-11e7-9a76-5966b98aed2c.jpg)

**Comment by phreesoft** [comment]
I believe there is a tool in the PhreeBooks settings that will fix this (under Journal tools). Make sure you have a back up before you run the tool.

Dave

**Comment by fguzman84** [comment]
Dear Dave,

First of all, thank you for your quick response.
I tried to do it with the options you mention. But the problem continues..I'll be selecting the right option?
attach you will find the options that I select,
Thank you!
![phreebooks trial balance error2](https://user-images.githubusercontent.com/31140022/29472057-0eeb5a76-8418-11e7-9ff6-b2eb69a257e3.jpg)

**Comment by phreesoft** [comment]
What version are your running?

**Comment by fguzman84** [comment]
Hi Dave, 

PhreeSoft Small Business Solutions (3.6) 
Best Regards!

**Comment by phreesoft** [comment]
I don’t see the tool. I must have added it to Release 3.7 or Bizuno. Anyway without digging deep into the DB, the next thing to try is print out your audit log report and see what the last transaction you did was. Delete the transaction and see if it clears up. This looks like a rounding error, what is your currency? how many digits do you have typically before the decimal point?

If you are not in period 8, the error may be a result of cogs clean-up from a recent purchase. In this case, the fix is beyond the scope of this issue tracker. 

I no longer support PhreeBooks. If you are interested in switching to Bizuno, I can help with that.

Dave

**Comment by ReneKervezee** [comment]
run the following sql
this will find the journal that is out of balance. 
If one is out of balance.

`SELECT m.id, sum( i.debit_amount ) , sum( i.credit_amount )
FROM `journal_item` i
JOIN journal_main m ON i.ref_id = m.id
GROUP BY m.id
HAVING STRCMP(sum( i.debit_amount ) , sum( i.credit_amount ) )
`
