### ISSUE TITLE
Recurring Transactions

### ISSUE THREAD

**Issue by felsenstein** [phreebooks/PhreeBooksERP#256]
Long time user of Phreebooks.  Really like using it.  Been doing a lot of tests before migrating from 3.7.

When posting recurring transactions in Purchasing and General Ledger modules, no matter what frequency I choose, the generated transactions end up being weekly.    I tried all the frequencies, and all resulted in weekly transactions in both modules.

Thank you for all your hard work.

**Comment by phreesoft** [comment]
Right you are. I will get it fixed in the next release. If you need it sooner, I can send you the fix. If you are using BIzuno on the PhreeSoft portal, the fix will be uploaded shortly. It is in a javascript file so it might take a few days to reload in the browser cache or you can reload manually.

Dave

**Comment by felsenstein** [comment]
Thanks!  I can wait for the next release.  I'm just testing right now.

**Comment by felsenstein** [comment]
This works good now in the new version, thank you!
