### ISSUE TITLE
resurrect zen cart connector

### ISSUE THREAD

**Issue by lankeeyankee** [phreebooks/PhreeBooksERP#267]
What is the possibility of resurrecting the zen cart connector that v3 used to have? If it's not worth your time, do you have API docs so we can develop one?

**Comment by phreesoft** [comment]
I do not have any users that have requested a Zen-Cart interface, you are the first. Since the demand is low I will not be developing the interface for release with Bizuno. I can program one to your version fro $200 or if you want to do it, I would start with the Bizuno API plugin for WordPress and use the bizuno-lib.php script as a base. I do not have any formal documentation on how to develop using the Bizuno API.

Dave
